galaxy_uwsgi:
  socket: :5555
  buffer-size: 16384
  processes: 1
  threads: 4
  offload-threads: 2
  static-map: /static=static
  static-map: /favicon.ico=static/favicon.ico
  master: false
  virtualenv: .venv
  pythonpath: lib
  thunder-lock: false
  die-on-term: true
  hook-master-start: unix_signal:2 gracefully_kill_them_all
  hook-master-start: unix_signal:15 gracefully_kill_them_all
  py-call-osafterfork: true
  enable-threads: true

galaxy:
  tool_dependency_dir: /tool_deps
  tool_data_table_config_path: /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml

pulsar:
  conda_auto_init: True
  conda_auto_install: True
  tool_dependency_dir: dependencies
  dependency_resolvers_config_file: config/dependency_resolvers_conf.xml

# Probably needs more polishing, but at least it works..
slurm:
  ControlMachine: "slurmctld"
  AuthType: "auth/munge"
  CacheGroups: "0"
  CryptoType: "crypto/munge"
  MpiDefault: "none"
  ProctrackType: "proctrack/pgid"
  ReturnToService: "1"
  SlurmctldPidFile: "/var/run/slurmctld.pid"
  SlurmctldPort: "6817"
  SlurmdPidFile: "/var/run/slurmd.pid"
  SlurmdPort: "6818"
  SlurmdSpoolDir: "/tmp/slurmd"
  SlurmUser: "slurm"
  StateSaveLocation: "/tmp/slurm"
  SwitchType: "switch/none"
  TaskPlugin: "task/none"
  InactiveLimit: "0"
  KillWait: "30"
  MinJobAge: "300"
  SlurmctldTimeout: "120"
  SlurmdTimeout: "300"
  Waittime: "0"
  FastSchedule: "1"
  SchedulerType: "sched/backfill"
  SchedulerPort: "7321"
  SelectType: "select/cons_res"
  SelectTypeParameters: "CR_Core_Memory"
  AccountingStorageType: "accounting_storage/none"
  AccountingStoreJobComment: "YES"
  ClusterName: "Cluster"
  JobCompType: "jobcomp/none"
  JobAcctGatherFrequency: "30"
  JobAcctGatherType: "jobacct_gather/none"
  SlurmctldDebug: info
  SlurmdDebug: info

htcondor_galaxy:
  CONDOR_HOST: "htcondor-master"
  ALLOW_ADMINISTRATOR: "*"
  ALLOW_OWNER: "*"
  ALLOW_READ: "*"
  ALLOW_WRITE: "*"
  ALLOW_CLIENT: "*"
  ALLOW_NEGOTIATOR: "*"
  DAEMON_LIST: "MASTER, SCHEDD"
  UID_DOMAIN: "galaxy"
  DISCARD_SESSION_KEYRING_ON_STARTUP: "False"
  TRUST_UID_DOMAIN: "true"

htcondor_master:
  BASE_CGROUP: ""
  CONDOR_HOST: "$(FULL_HOSTNAME)"
  DAEMON_LIST: "MASTER, COLLECTOR, NEGOTIATOR, SCHEDD"
  DISCARD_SESSION_KEYRING_ON_STARTUP: "False"
  TRUST_UID_DOMAIN: "True"
  ALLOW_ADMINISTRATOR: "*"
  ALLOW_OWNER: "*"
  ALLOW_READ: "*"
  ALLOW_WRITE: "*"
  ALLOW_NEGOTIATOR: "*"
  ALLOW_NEGOTIATOR_SCHEDD: "*"
  ALLOW_WRITE_COLLECTOR: "*"
  ALLOW_WRITE_STARTD: "*"
  ALLOW_READ_COLLECTOR: "*"
  ALLOW_READ_STARTD: "*"
  ALLOW_CLIENT: "*"
  DOCKER_IMAGE_CACHE_SIZE: "20"
  UID_DOMAIN: "galaxy"
  TRUST_UID_DOMAIN: "TRUE"

htcondor_executor:
  CONDOR_HOST: "htcondor-master"
  DAEMON_LIST: "MASTER, STARTD"
  DISCARD_SESSION_KEYRING_ON_STARTUP: "False"
  TRUST_UID_DOMAIN: "true"
  NUM_SLOTS: "1"
  NUM_SLOTS_TYPE_1: "1"
  BASE_CGROUP: ""
  ALLOW_ADMINISTRATOR: "*"
  ALLOW_OWNER: "*"
  ALLOW_READ: "*"
  ALLOW_WRITE: "*"
  ALLOW_CLIENT: "*"
  ALLOW_NEGOTIATOR_SCHEDD: "*"
  ALLOW_WRITE_COLLECTOR: "*"
  ALLOW_WRITE_STARTD: "*"
  ALLOW_READ_COLLECTOR: "*"
  ALLOW_READ_STARTD: "*"
  UID_DOMAIN: "galaxy"
  SCHED_NAME: "htcondor-master"
