# Extend Pulsar to use RabbitMQ (Message Queue) instead of the REST API
# for communicating with Galaxy.
# Requirements: `docker-compose.pulsar.yml`
# Example: `docker-compose -f docker-compose.yml -f docker-compose.pulsar.yml -f docker-compose.pulsar.mq.yml up`
version: "3.7"
services:
  galaxy-configurator:
    environment:
      - GALAXY_JOB_RUNNER=pulsar_mq
      - PULSAR_CONFIG_MESSAGE_QUEUE_URL=amqp://pulsar:8jfqi9uo2i30fqoifqfo09@pulsar-rabbitmq/pulsar
      - PULSAR_GALAXY_URL=http://nginx:80
  pulsar-rabbitmq:
    image: rabbitmq:alpine
    container_name: pulsar-rabbitmq
    hostname: pulsar-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=pulsar
      - RABBITMQ_DEFAULT_PASS=8jfqi9uo2i30fqoifqfo09
      - RABBITMQ_DEFAULT_VHOST=pulsar
    volumes:
      - ${EXPORT_DIR:-./export}/pulsar_rabbitmq:/var/lib/rabbitmq:delegated
    networks:
      - galaxy
